### VERSION 1.4-Beta

countdown-time: 5
enable-world: "mushm"

materials:
  # ยากมาก Yellow
  workshop_six:glow_mushroom_patch_large:
    command: "mmoitems give MATERIAL MUSHROOM_LV4 %player% 1 0 100 0 silent"
    cooldown-time: 10
    success-rate: 50.0
  workshop_six:glow_mushroom_patch:
    command: "mmoitems give MATERIAL MUSHROOM_LV4 %player% 1 0 100 0 silent"
    cooldown-time: 10
    success-rate: 55.0
  # ยาก Orange
  workshop_six:orange_mushroom_patch_large:
    command: "mmoitems give MATERIAL MUSHROOM_LV3 %player% 1 0 100 0 silent"
    cooldown-time: 8
    success-rate: 50.0
  workshop_six:orange_mushroom_patch:
    command: "mmoitems give MATERIAL MUSHROOM_LV3 %player% 1 0 100 0 silent"
    cooldown-time: 8
    success-rate: 50.0
  # กลาง Red
  workshop_six:red_mushroom_patch_large:
    command: "mmoitems give MATERIAL MUSHROOM_LV2 %player% 1 0 100 0 silent"
    cooldown-time: 5
    success-rate: 65.0
  workshop_six:red_mushroom_patch:
    command: "mmoitems give MATERIAL MUSHROOM_LV2 %player% 1 0 100 0 silent"
    cooldown-time: 5
    success-rate: 70.0
  # ง่าย Brown
  workshop_six:brown_mushroom_patch_large:
    command: "mmoitems give MATERIAL MUSHROOM_LV1 %player% 1 0 100 0 silent"
    cooldown-time: 3
    success-rate: 80.0
  workshop_six:brown_mushroom_patch:
    command: "mmoitems give MATERIAL MUSHROOM_LV1 %player% 1 0 100 0 silent"
    cooldown-time: 3
    success-rate: 85.0

hologram:
  ready: "§aเห็ดพร้อมเก็บเกี่ยวแล้ว!"
  cooldown: "§cเห็ดกำลังโต! กรุณารอสักครู่"

harvest-messages:
  countdown-title: "§e%time%"
  countdown-subtitle: "§aคุณกำลังเก็บเห็ด อดทนหน่อยนะ"
  countdown:
    5: "&c"
    4: "&a&c"
    3: "&a&c"
    2: "&a&c"
    1: "&a&c"
  success-title: "§aคุณได้ทำการเก็บเห็ดแล้ว!"
  success-subtitle: "§eอย่าเผลอกินเข้าไปล่ะ!"
  fail-title: "§cคุณเผลอทำเห็ดหลุดมือ!"
  fail-subtitle: "§eคราวหลังก็ระวังด้วยล่ะ!"
  cooldown-title: "§cเห็ดกำลังโต! กลับมาในภายหลังนะ"
  cooldown-subtitle: "§eเห็ดจะโตในอีก: %time%"
  already-harvesting-title: "§cคุณเก็บเห็ดได้ทีละต้นเท่านั้นนะ!"
  already-harvesting-subtitle: "§eคุณกำลังเก็บเห็ดอีกต้นอยู่แล้ว!"
  active-player-title: "§cมีคุณกำลังเก็บเห็ดต้นนี้อยู่แล้ว!"
  active-player-subtitle: "§eผู้เล่นที่กําลังเก็บเกี่ยว §f%player%"
  move-title: "§cคุณเผลอทำเห็ดหลุดมือ!"
  move-subtitle: "§eการเก็บเห็ดถูกยกเลิก! น่าเสียดาย"

failed-command:
  1: "playsound mminecraft:entity.villager.no player %player% %player_x% %player_y% %player_z%"
  2: "playsound minecraft:entity.villager.celebrate player %player% %player_x% %player_y% %player_z%"

custom-sound:
  console-command:
    enabled: true
    5: "playsound minecraft:block.note_block.pling player %player% %player_x% %player_y% %player_z%"
    4: "playsound minecraft:block.note_block.pling player %player% %player_x% %player_y% %player_z%"
    3: "playsound minecraft:block.note_block.pling player %player% %player_x% %player_y% %player_z%"
    2: "playsound minecraft:block.note_block.pling player %player% %player_x% %player_y% %player_z%"
    1: "playsound minecraft:block.note_block.pling player %player% %player_x% %player_y% %player_z%"
    0: "playsound minecraft:block.note_block.bell player %player% %player_x% %player_y% %player_z%"

messages:
  reload-success: "ทำการรีโหลด Config และการตั้งค่าสำเร็จ!"
  reload-usage: "§cAn internal error occurred while attempting to perform this command."
  no-hologram: "§cAn internal error occurred while attempting to perform this command."

# © 2025 zPleum. Licensed under MIT License. | https://zpleum.site/

